#all declared paths are exemplary. Feel free to change them.
image_format: ".tif"                                                          # image format for all subprocesses

preprocessor:
  buffer_size: 0                                                              # buffer size in pixels
  step_size: 256                                                              # step size for tiling in x- and y-direction
  channel_idx: [1, 2, 3]                                                      # channel selection to create input rgb image  
  resample_size: 0.3                                                          # pixel size in image units after resampling
  image_dir: ./data/input/images                                              # image directory for preprocessing 
  #target_dir: ./data/input/targets                                           # target directory for preprocessing.
  output_dir: ./data/output/preprocessed/train                                # output directory
  keep_empty: false                                                           # by default, empty images are discarded

model:
  rank: 512                                                                   # LoRA adaptor rank
  device: cuda                                                                # device for model and data. if device: cuda and torch.cuda.is_available() then GPU is used for training/inference
  load_pth_from: "./pretrained/sam_vit_b_01ec64.pth"                          # pth load path for loading foundation SAM model weights
  load_checkpoint_from: "./pretrained/buildingSAM_R512.safetensors"           # checkpoint path to load adapter weights from
  
training:
    model_dir: ./data/output/myFirstModel                                     # output directory for model checkpoints
    batch_size: 2
    num_epochs: 100
    learning_rate: 0.0001
    save_model_each_n_epoch: 1                                                # checkpoint frequency
    #tensorboard_log_dir: ./data/output/logs                                  # output directory for tensorboard logs
    augmentations:                                                            # list of train time augmentations (see albumentations.ai for more information)
        - name: RandomSizedCrop
          min_max_height: [1024, 5000]
          size: [1024, 1024]
          p: 1.0
        - name: HorizontalFlip
          p: 0.25
        - name: VerticalFlip
          p: 0.25
        - name: RandomRotate90
          p: 0.5
        - name: Transpose
          p: 0.25
        - name: RandomBrightnessContrast
          p: 0.5
        - name: CoarseDropout
          num_holes_range: [5, 10]
          hole_height_range: [32, 64]
          hole_width_range: [32, 64]
          p: 1.0
    trainDataset:
      image_dir: ./data/output/preprocessed/train/images
      target_dir: ./data/output/preprocessed/train/targets
    #valDataset:
      #image_dir: ./data/output/preprocessed/val/images
      #target_dir: ./data/output/preprocessed/val/targets
    #visualization:                                                            # write intermediate results during training to disk
        #output_type: probs
        #output_dir: ./data/output/train/intermediates
        #frequency: 2

inference:
    output_type: probs 
    image_dir: ./data/output/preprocessed/train/images
    output_dir: ./data/output/inference/
    augmentations:                                                            # test time augmentation
        - HorizontalFlip
        - VerticalFlip
        - RandomRotate90

postprocessor:
  output_type: probs
  threshold: 0                                                                # threshold value. Only used when output_type=masks
  image_dir: ./data/output/inference/
  output_dir: ./data/output/postprocessed